# <center> Numpy Basics </center>

In [286]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [287]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
arr = np.array([1,2,3])
arr


array([1, 2, 3])

In [288]:
# print output
arr


array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [289]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [290]:
#print dimentions of a,b, c and d
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [291]:
# print shape of each a,b ,c and d
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [292]:
# print data type of c and d
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int32
int32
int32
int32


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [293]:
#print type of a and b variable
print(type(a))
print(type(b))





<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [294]:
# Lets check length of array b, using len() function
len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy. 

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [295]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [296]:
#code here as instructed above
%timeit [l1[i] * l2[i] for i in range(len(l1))]

295 ns ± 5.91 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [297]:
[l1[i] * l2[i] for i in range(len(l1))]

[400, 1000, 1800]

Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [298]:
%timeit [l3[i] * l4[i] for i in range(len(l3))]

587 ns ± 0.959 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [299]:
[l3[i] * l4[i] for i in range(len(l3))]

[400, 1000, 1800]

Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [300]:
#Create a numpy array using arange with 1 and 11 as parameter in it


arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [301]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
arr = np.arange(1,11,2)
arr



array([1, 3, 5, 7, 9])

In [302]:
# create numpy array using eye function with 3 as passed parameter


np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [303]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1,17)
x



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [304]:
# Reshape x with 2 rows and 8 columns
x.reshape(2,8)


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [305]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x.reshape(2,4,2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [306]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x.reshape(4,4)



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [307]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y = np.arange(1,25)
y.reshape(3,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [308]:
# Flattening y
y.flatten()



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [309]:
# Create an array a with all even numbers between 1 to 17
a = np.array([a for a in range(1,17) if a%2 == 0])


In [310]:
# Get third element in array a
a[2]

6

In [311]:
#Print 3rd, 5th, and 7th element in array a
a[2:7:2]


array([ 6, 10, 14])

Lets check the same for 2 D array

In [312]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [313]:
# print the 3rd element from the 3rd row of a
a[2][2]


9

Well done!

Now lets check indexing for 3 D array 

In [314]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
b = np.array(b)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [315]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
b[0][1][2]

6

In [316]:
# Create 1D array

arr = np.arange(1,11)
arr  




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [317]:
# Slice elements from 1st to 5th element from the following array:

arr[0:5]



array([1, 2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.



In [318]:
# Slice elements from index 5 to the end of the array:
arr[5:]



array([ 6,  7,  8,  9, 10])

In [319]:
# Slice elements from the beginning to index 5 (not included):
arr[0:5]




array([1, 2, 3, 4, 5])

**STEP**

Use the step value to determine the step of the slicing:

In [320]:
# Print every other element from index 1 to index 7
arr[1:7:2]



array([2, 4, 6])

In [321]:
# Return every other element from the entire array arr:
arr[::2]



array([1, 3, 5, 7, 9])

well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [322]:
# Print array a
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [323]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
a[2][1:5]

array([8, 9])

In [324]:
# In array 'a' print index 2 from all the elements :
for i in a:
    print(i[1])

2
5
8


In [325]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
for i in a:
    print(i[1:])

[2 3]
[5 6]
[8 9]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [326]:
# x1= 
x1 = np.array([1,2,3])


In [327]:
# assign x2 = x1
x2 = x1


In [328]:
#print x1 and x2

print(x1)
print(x2)


[1 2 3]
[1 2 3]


Ok now you have seen that both of them are same 

In [329]:
# change 1st element of x2 as 10
x2[0] = 10



In [330]:
#Again print x1 and x2
print(x1)
print(x2)



[10  2  3]
[10  2  3]


In [331]:
# Check memory share between x1 and x2
print(id(x1))
print(id(x2))


2826592835056
2826592835056


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [332]:
# Create a view of x1 and store it in x3.
x3 = x1.view()


In [333]:
# Again check memory share between x1 and x3
print(id(x1))
print(id(x3))



2826592835056
2826592836208


Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [334]:
print(x1)

[10  2  3]


In [335]:
#Change 1st element of x3=200
x3[0] = 200

In [336]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)



[200   2   3]
[200   2   3]


Now its proved.

Lets see how **Copy()** function works

In [337]:
# Now create an array x4 which is copy of x1
x4= x1.copy()



In [338]:
# Change the last element of x4 as 900

x4[0] = 900



In [339]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)




[200   2   3]
[900   2   3]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [340]:
#Check memory share between x1 and x4
print(id(x1))
print(id(x4))


2826592835056
2826594111184


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [341]:
# stack x1 and x4 along columns.
np.vstack((x1,x4))

array([[200,   2,   3],
       [900,   2,   3]])

In [342]:
#stack x1 and x4 along rows
np.hstack((x1,x4))


array([200,   2,   3, 900,   2,   3])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [343]:
arr1 = np.arange(1,5) 


arr2 = np.arange(5,9)


##join arr1 and arr2 along rows using concatenate() function
np.concatenate((arr1, arr2), axis=0)



array([1, 2, 3, 4, 5, 6, 7, 8])

In [344]:
##join a and b along columns using concatenate() function
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [345]:
# append arr2 to arr1
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.append(arr2,arr1)

array([4, 5, 6, 1, 2, 3])

Lets use insert() function which Inserts values into array before specified index value

In [346]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [347]:
x2

array([200,   2,   3])

In [348]:
# delete 2nd element from array x2
np.delete(x2,1)

array([200,   3])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner! 